### ISSUE TITLE
ollama support

### ISSUE THREAD

**Issue by waikoo** [3v0k4/exit.nvim#3]
This is a great idea for a plugin!
Do you plan on supporting ollama models as well?

**Comment by 3v0k4** [comment]
Thanks, @waikoo 🙏

It would be great to support more models. Would you be willing to create a PR?

I guess we could use the [completion (no streaming)](https://github.com/ollama/ollama/blob/main/docs/api.md#request-no-streaming) endpoint for it.

You'd need to create a file similar to [openai.lua](https://github.com/3v0k4/exit.nvim/blob/27d5678deedd2218e8f6b978a42ccd7f31e368d2/lua/openai.lua) for ollama and use it in [exit.lua](https://github.com/3v0k4/exit.nvim/blob/27d5678deedd2218e8f6b978a42ccd7f31e368d2/lua/exit.lua#L3), which is the entrypoint of the plugin.

**Comment by waikoo** [comment]
I would be willing, @3v0k4 . So far I only forked and tweaked an existing colorscheme for nvim so I don't even know where to start. I'll look into the link you sent. Would you be willing to help a noob out? For example, where/how do I even start experimenting with the file similar to openai.lua? Do I go where the plugin is downloaded in ~/.local/share (if I'm not mistaken) and just start adding files?

**Comment by 3v0k4** [comment]
Nice progress!

It would be easier for me to look and play with the code.

Could you open a PR? We can move this discussion there.

When it comes to plugin development, I was either:
1. changing the source files in `~/.config/nvim/pack/minpac/start/exit.nvim` (I'm using minpac) and opening a new `nvim`
2. removing the import and reimporting it (see below)

In init, there's a `require('exit')`. So the package gets cached into `package.loaded`, which you can see in an nvim session with:

```
:lua vim.print(package.loaded)
```

Or:

```
:lua vim.print(package.loaded["exit"])
```

All the following `require`s use the cache and not the source anymore. But you can remove the record from the cache and reimport:

```
:lua package.loaded["exit"] = nil
:lua require("exit")
```

Or you can even call a function with:

```
:lua package.loaded["exit"] = nil
:lua require("exit").foo()
```
